#!/usr/bin/env python3
"""Fail-closed isolated deterministic reader build for R011-B017.

The exact admitted B016 source manifest is the immutable build base.  This
tool overlays only the bounded B017 negative-binomial section, its complete
EoCE file (exercises 27--30), and upstream-public answers 27 and 29.  It
verifies the pinned authority spans and the translation-candidate identities
before assembling an isolated source tree, performs two complete deterministic
LaTeX replays using the established workflow, checks source/reader language,
mathematics, identifiers, references, and exercise-answer closure, and writes
a sanitized receipt.

Every generated byte is confined to ``scratch/b017-build-candidate``.  The
canonical repo, backend, controls, output, release, Git, network, credentials,
and upstream services are neither read as build authority nor mutated.
"""

from __future__ import annotations

import hashlib
import json
import math
import re
import shutil
import subprocess
import sys
from collections import Counter
from pathlib import Path
from typing import Any, Iterable


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
import build_b012_candidate as shared  # noqa: E402


BOUNDARY_ID = "R011-B017"
MODEL = "OpenAI Codex gpt-5.6-sol, Ultra"
AUTHORITY_COMMIT = "fee25091fb24e89c36296fd67c48c1fcf7a93b6e"
AUTHORITY_TREE = "d61cc601e7d97759ce805900520f784d02a0489e"

BASE_SNAPSHOT = ROOT / "qa/b016-build/source-snapshot-b016"
BASE_MANIFEST = ROOT / "qa/b016-build/R011-B016_SOURCE_MANIFEST.tsv"
BASE_SOURCE_QA = ROOT / "qa/b016-build/R011-B016_SOURCE_QA.json"
BASE_BUILD_RECEIPT = ROOT / "qa/b016-build/final/CANDIDATE_BUILD_QA_B016.json"
BASE_PDF = ROOT / "qa/b016-build/final/main.pdf"
BASE_TEXT = ROOT / "qa/b016-build/final/main-final.txt"
BASE_VISUAL_QA = ROOT / "qa/b016-visual/R011-B016_VISUAL_QA.json"
BASE_BOUNDARY_RECEIPT = ROOT / "qa/R011-B016_BOUNDARY_RECEIPT.json"
BASE_POST_ADMISSION = ROOT / "qa/b016-admission/R011-B016_POST_ADMISSION_VERIFICATION.json"

AUTHORITY_ROOT = ROOT / f"authority/upstream/openintro-statistics-{AUTHORITY_COMMIT}"
AUTHORITY_MAIN = AUTHORITY_ROOT / "ch_distributions/TeX/ch_distributions.tex"
AUTHORITY_EOCE = AUTHORITY_ROOT / "ch_distributions/TeX/negative_binomial_distribution.tex"
AUTHORITY_ANSWERS = AUTHORITY_ROOT / "extraTeX/eoceSolutions/eoceSolutions.tex"

CANDIDATE = ROOT / "scratch/b017-candidate"
BLUEPRINT = ROOT / "scratch/b017-source/R011-B017_BOUNDARY_BLUEPRINT.json"
MAIN_FRAGMENT = CANDIDATE / "R011-B017_ch_distributions_1927-2110_CANDIDATE.tex"
EOCE_FRAGMENT = CANDIDATE / "R011-B017_negative_binomial_distribution_CANDIDATE.tex"
ANSWER_FRAGMENT = CANDIDATE / "R011-B017_eoceSolutions_750-761_CANDIDATE.tex"
CANDIDATE_QA = CANDIDATE / "R011-B017_CANDIDATE_QA.json"
CANDIDATE_RECEIPT = CANDIDATE / "R011-B017_CANDIDATE_RECEIPT.json"
RESIDUAL_REVIEW = CANDIDATE / "R011-B017_RESIDUAL_ENGLISH_REVIEW.tsv"
CORRECTIONS = CANDIDATE / "R011-B017_UPSTREAM_CORRECTION_CANDIDATES.json"

BUILD_ROOT = ROOT / "scratch/b017-build-candidate"
SNAPSHOT = BUILD_ROOT / "source-snapshot-b017"
SOURCE_MANIFEST = BUILD_ROOT / "R011-B017_SOURCE_MANIFEST.tsv"
SOURCE_QA = BUILD_ROOT / "R011-B017_SOURCE_QA.json"
RUN_A = BUILD_ROOT / "replay-a"
RUN_B = BUILD_ROOT / "replay-b"
FINAL = BUILD_ROOT / "final"
FINAL_PDF = FINAL / "main.pdf"
FINAL_TEXT = FINAL / "main-final.txt"
BUILD_RECEIPT = FINAL / "CANDIDATE_BUILD_QA_B017.json"
FINAL_BUILD_RECEIPT = FINAL / "CANDIDATE_BUILD_QA_B017_FINAL.json"
REVIEW_RENDER = BUILD_ROOT / "review-render"
VISUAL_QA = BUILD_ROOT / "R011-B017_VISUAL_QA.json"
REVIEW_DPI = 180

# Exact preimages permitted for the one-time B016-parity metadata upgrade.
# No PDF, source, replay, render, or other receipt preimage is writable through
# this exception.
PRE_ADMISSION_FLAG_VISUAL_QA = (
    4426,
    "3250ae2785a5d236959a853d510e7b3c5868f16aa811179bed90a2cfa758e751",
)
PRE_ADMISSION_FLAG_FINAL_RECEIPT = (
    19549,
    "43c8960be3294d0b52f9641aba07787932a6caf847e5b8e9c76e49676b02820a",
)

MAIN_PATH = "ch_distributions/TeX/ch_distributions.tex"
EOCE_PATH = "ch_distributions/TeX/negative_binomial_distribution.tex"
ANSWERS_PATH = "extraTeX/eoceSolutions/eoceSolutions.tex"
MODIFIED_PATHS = {MAIN_PATH, EOCE_PATH, ANSWERS_PATH}

BASE_FILES: dict[Path, tuple[int, str]] = {
    BASE_MANIFEST: (175582, "585af590a512c43480a4b5cfe1efc40e34204b38a1c2a8beffde4dfef733c2c0"),
    BASE_SOURCE_QA: (15681, "d92a7873ca39b1f470b07b27954bf8a5bc2d445f7369086d1b278ebae41e2a13"),
    BASE_BUILD_RECEIPT: (23967, "ba5396c54f696ec43c18eba16a70f1036861910264e52f761ee55e7b70971a03"),
    BASE_PDF: (22033206, "35e67115eb538568de50afab1a9b927f0138909b287f059524386bfac89fe615"),
    BASE_TEXT: (1595432, "899db52d31ce1fc7b58abe92b872acc623414365e817bd0cd523be2d2903eea6"),
    BASE_VISUAL_QA: (23362, "f313b0379d6618f31c6aceb06c776d1001bbbc2092905bf0dff876917b1cabf9"),
    BASE_BOUNDARY_RECEIPT: (14638, "3ed6f2bd4f960725b28c692b2b0ff836f1f1b4c05089e1a20412b0ba14cede4f"),
    BASE_POST_ADMISSION: (2579, "a17feae958f086585af2ea05bc8ed1788b14f264824e8540447f3dcb1ccdb4dd"),
}

AUTHORITY_FILES: dict[Path, tuple[int, str]] = {
    AUTHORITY_MAIN: (91188, "71e4985a1bf31e9dd6897ec2bd246b3b2f8cd62ab55524a5b1bfe791e613a3a9"),
    AUTHORITY_EOCE: (2860, "4d6bf067db161507dbe9555a1d31ae0c220152d00ff8d1ac62800adafa7571a1"),
    AUTHORITY_ANSWERS: (106045, "6c4e01376db4c023cc7b3f9949490e57220ef1cb831c580da71efde6ce723268"),
}

CANDIDATE_FILES: dict[Path, tuple[int, str]] = {
    BLUEPRINT: (12381, "27f4b8d560e57af1fffb2fddb5974382ffbe8ec515a9a2209cde4dc3dfa6a0bf"),
    MAIN_FRAGMENT: (11506, "ab47c5a5523385ad139330369a6c55fda872d4eececda05f95f02a29d40300a9"),
    EOCE_FRAGMENT: (2960, "328f2299f3a62823f5d3aa3f4381a04c1d54dc1e03ef0443567f63e47a0455e7"),
    ANSWER_FRAGMENT: (646, "77bb219a207b4a1918a7343e3aec09d6851e10f50e6054eb87289c781b456696"),
    CANDIDATE_QA: (8163, "93b2b3e038020c48a6ed5e0afaf4ef433d9f7b00093945fe4c5e50699447b1fe"),
    CANDIDATE_RECEIPT: (8066, "094dea75910939cce90287bb0a547260dcd385413759cece40bed36b5fc1ef22"),
    RESIDUAL_REVIEW: (1798, "90bdc66f3d8c7f3a727f3bb1ba6af49eada746d4bd44e20f77334687a03163fb"),
    CORRECTIONS: (5178, "b2def77d1d2f4a9328590c4570e3a3ed34a0d2241e5a444f8ab51fb952b9d714"),
}

BASE_MANIFEST_ANCHORS: dict[str, tuple[int, str]] = {
    MAIN_PATH: (94278, "a899b2e0a0851d7a0c9b4be78e7c1c0547eb4575c133194ae1202ff13e8f827f"),
    EOCE_PATH: (2860, "4d6bf067db161507dbe9555a1d31ae0c220152d00ff8d1ac62800adafa7571a1"),
    ANSWERS_PATH: (109526, "f61ea0b074cd65d6bb5974814f96e75f1359e4ef840c2908bf5bfc7deaebceb1"),
}

SOURCE_SPANS: dict[str, tuple[Path, int, int, str]] = {
    "main": (AUTHORITY_MAIN, 1927, 2110, "7a53ff55c8ca52d2c7ef8d21444bd868307bcd44eb0bf6038fd66d8cab05eaca"),
    "eoce": (AUTHORITY_EOCE, 1, 70, "b85786a453fd3b7ba041f4c98d7df8f0c270b212bb9fc905a10bc92e3cf57899"),
    "answers": (AUTHORITY_ANSWERS, 750, 761, "aacce7bc059c58d910f2e97049e003d3f844f780aa1d19a181e4e14f7a379f17"),
}

GateError = shared.GateError
require = shared.require
identity = shared.identity
require_exact = shared.require_exact
read_json = shared.read_json
canonical_json = shared.canonical_json
rel = shared.rel


def configure_shared() -> None:
    """Bind the proven shared toolchain runner to this isolated build root."""
    shared.ROOT = ROOT
    shared.BOUNDARY_ID = BOUNDARY_ID
    shared.MODEL = MODEL
    shared.AUTHORITY_COMMIT = AUTHORITY_COMMIT
    shared.AUTHORITY_TREE = AUTHORITY_TREE
    shared.BASE_SNAPSHOT = BASE_SNAPSHOT
    shared.BASE_MANIFEST = BASE_MANIFEST
    shared.BASE_SOURCE_QA = BASE_SOURCE_QA
    shared.BASE_BUILD_RECEIPT = BASE_BUILD_RECEIPT
    shared.BASE_PDF = BASE_PDF
    shared.BUILD_ROOT = BUILD_ROOT
    shared.SNAPSHOT = SNAPSHOT
    shared.SOURCE_MANIFEST = SOURCE_MANIFEST
    shared.SOURCE_QA = SOURCE_QA
    shared.RUN_A = RUN_A
    shared.RUN_B = RUN_B
    shared.FINAL = FINAL
    shared.FINAL_PDF = FINAL_PDF
    shared.FINAL_TEXT = FINAL_TEXT
    shared.BUILD_RECEIPT = BUILD_RECEIPT
    shared.REVIEW_RENDER = REVIEW_RENDER


configure_shared()


def require_build_path(path: Path) -> None:
    try:
        path.resolve().relative_to(BUILD_ROOT.resolve())
    except ValueError as exc:
        raise GateError(f"write path escapes isolated B017 build root: {path}") from exc


def load_manifest() -> dict[str, tuple[int, str]]:
    rows: dict[str, tuple[int, str]] = {}
    for line_number, line in enumerate(BASE_MANIFEST.read_text(encoding="utf-8").splitlines(), 1):
        parts = line.split("\t")
        require(len(parts) == 3, f"malformed B016 source manifest line {line_number}")
        path, size_text, digest = parts
        require(path not in rows, f"duplicate B016 manifest path: {path}")
        require(re.fullmatch(r"[0-9a-f]{64}", digest) is not None, f"invalid B016 manifest digest on line {line_number}")
        rows[path] = (int(size_text), digest)
    require(len(rows) == 1206, f"B016 source manifest row count changed: {len(rows)}")
    require(MODIFIED_PATHS <= rows.keys(), "one or more B017 overlay paths are outside the B016 closure")
    for path, expected in BASE_MANIFEST_ANCHORS.items():
        require(rows.get(path) == expected, f"B016 manifest anchor changed: {path}")
    return rows


def verify_base(rows: dict[str, tuple[int, str]]) -> dict[str, Any]:
    files = {rel(path): require_exact(path, size, digest) for path, (size, digest) in BASE_FILES.items()}
    require(BASE_SNAPSHOT.is_dir(), "admitted B016 source snapshot absent")
    snapshot = shared.verify_manifest_snapshot(BASE_SNAPSHOT, rows)
    build = read_json(BASE_BUILD_RECEIPT)
    visual = read_json(BASE_VISUAL_QA)
    boundary = read_json(BASE_BOUNDARY_RECEIPT)
    post = read_json(BASE_POST_ADMISSION)
    require(build.get("boundary_id") == "R011-B016", "B016 build receipt boundary changed")
    require(build.get("status") == "PASS_ISOLATED_TWO_REPLAY_DETERMINISTIC_BUILD_VISUAL_INSPECTION_PENDING", "B016 build receipt status changed")
    require(build.get("page_count") == 428, "B016 base reader page count changed")
    require(visual.get("status") == "PASS_ZERO_VISUAL_DEFECTS_IN_BOUNDARY_ASSET_AND_TRANSITION_WINDOWS", "B016 visual base is not terminal PASS")
    require(boundary.get("status") == "admitted_exact_pdf_source_and_backend", "B016 boundary is not admitted")
    require(post.get("status") == "PASS_VERIFIED_ADMITTED_EXACT", "B016 post-admission evidence is not exact PASS")
    require(post.get("next_cursor", {}).get("label") == "negativeBinomial", "B016 next cursor changed")
    require(post.get("verification", {}).get("pages") == 428, "B016 post-admission page count changed")
    require(post.get("verification", {}).get("source_overlays") == 4, "B016 source overlay closure changed")
    return {
        "boundary_id": "R011-B016",
        "files": files,
        "snapshot": {"path": rel(BASE_SNAPSHOT), **snapshot},
        "manifest_paths_verified_exact": len(rows),
        "build_status": build["status"],
        "visual_status": visual["status"],
        "boundary_status": boundary["status"],
        "post_admission_status": post["status"],
        "page_count": 428,
        "next_cursor": "negativeBinomial",
    }


def source_span(path: Path, start: int, end: int) -> str:
    lines = path.read_text(encoding="utf-8-sig").splitlines()
    require(1 <= start <= end <= len(lines), f"source span outside file: {rel(path)}:{start}-{end}")
    return "\n".join(lines[start - 1 : end])


def command_multiset(value: str) -> Counter[str]:
    return Counter(re.findall(r"\\(?:[A-Za-z@]+|.)", value))


def environment_sequence(value: str) -> list[tuple[str, str]]:
    return re.findall(r"\\(begin|end)\{([^{}]+)\}", value)


def argument_sequence(value: str, command: str) -> list[str]:
    return re.findall(rf"\\{re.escape(command)}\{{([^{{}}]+)\}}", value)


def numeric_sequence(value: str) -> list[str]:
    return re.findall(r"(?<![A-Za-z])(?:\d+(?:\.\d+)?|\.\d+)", value)


def brace_balance(value: str) -> int:
    unescaped = re.sub(r"\\[{}]", "", value)
    return unescaped.count("{") - unescaped.count("}")


def verify_structure(role: str, source: str, target: str) -> dict[str, Any]:
    source_commands = command_multiset(source)
    target_commands = command_multiset(target)
    require(source_commands == target_commands, f"{role} LaTeX command multiset changed")
    require(environment_sequence(source) == environment_sequence(target), f"{role} environment order changed")
    identifiers: dict[str, list[str]] = {}
    for command in ("label", "ref", "pageref", "input"):
        source_values = argument_sequence(source, command)
        target_values = argument_sequence(target, command)
        require(source_values == target_values, f"{role} {command} sequence changed")
        identifiers[command] = target_values
    # Reader-facing prose legitimately localizes some digit forms to Indonesian
    # words (for example, "4 conditions" -> "empat syarat").  Formula
    # preservation is therefore proved separately below by bound formula
    # witnesses and independent recomputation, rather than by a false global
    # prose-token equality requirement.
    source_numbers = numeric_sequence(source)
    target_numbers = numeric_sequence(target)
    require(brace_balance(source) == brace_balance(target) == 0, f"{role} brace balance failed")
    return {
        "command_multiset_equal": True,
        "environment_order_equal": True,
        "identifier_order_equal": True,
        "global_numeric_token_equality_not_asserted_due_to_prose_localization": True,
        "brace_balance": 0,
        "identifiers": identifiers,
        "command_occurrences": sum(source_commands.values()),
        "environment_events": len(environment_sequence(source)),
        "source_numeric_tokens": len(source_numbers),
        "target_numeric_tokens": len(target_numbers),
    }


def verify_inputs() -> dict[str, Any]:
    authority = {rel(path): require_exact(path, size, digest) for path, (size, digest) in AUTHORITY_FILES.items()}
    exact = {rel(path): require_exact(path, size, digest) for path, (size, digest) in CANDIDATE_FILES.items()}
    spans: dict[str, str] = {}
    span_receipts: dict[str, Any] = {}
    for role, (path, start, end, expected) in SOURCE_SPANS.items():
        value = source_span(path, start, end)
        raw = value.encode("utf-8")
        digest = hashlib.sha256(raw).hexdigest()
        require(digest == expected, f"pinned {role} authority span changed")
        spans[role] = value
        span_receipts[role] = {
            "path": rel(path),
            "lines": f"{start}-{end}",
            "line_count": end - start + 1,
            "utf8_lf_no_terminal_newline_bytes": len(raw),
            "sha256": digest,
        }

    blueprint = read_json(BLUEPRINT)
    receipt = read_json(CANDIDATE_RECEIPT)
    qa = read_json(CANDIDATE_QA)
    corrections = read_json(CORRECTIONS)
    require(blueprint.get("status") == "READY_FOR_TRANSLATION", "B017 boundary blueprint is not ready")
    require(blueprint.get("boundary", {}).get("id") == BOUNDARY_ID, "B017 blueprint boundary changed")
    require(blueprint.get("boundary", {}).get("next_cursor", {}).get("label") == "poisson", "B017 blueprint next cursor changed")
    require(receipt.get("status") == "COMPLETE_BOUNDED_CANDIDATE_NOT_ADMITTED", "B017 candidate receipt status changed")
    require(receipt.get("unresolved_issues") == [], "B017 candidate reports unresolved issues")
    require(qa.get("status") == "PASS_BOUNDED_TRANSLATION_CANDIDATE", "B017 candidate QA is not PASS")
    require(qa.get("unresolved_issues") == [], "B017 candidate QA reports unresolved issues")
    require(corrections.get("status") == "RECORDED_NOT_APPLIED_TO_AUTHORITY", "B017 upstream corrections status changed")
    require(corrections.get("candidate_count") == corrections.get("high_confidence_count") == 8, "B017 upstream correction count changed")
    require(corrections.get("semantic_correction_count") == 0, "B017 correction ledger now contains a semantic change")
    require(MODEL in json.dumps([blueprint, receipt], ensure_ascii=False), "exact model provenance absent from B017 controls")

    targets = {
        "main": MAIN_FRAGMENT.read_text(encoding="utf-8"),
        "eoce": EOCE_FRAGMENT.read_text(encoding="utf-8"),
        "answers": ANSWER_FRAGMENT.read_text(encoding="utf-8"),
    }
    expected_lines = {"main": 184, "eoce": 70, "answers": 12}
    structures: dict[str, Any] = {}
    for role in ("main", "eoce", "answers"):
        require(len(targets[role].splitlines()) == expected_lines[role], f"{role} candidate line count changed")
        structures[role] = verify_structure(role, spans[role], targets[role].rstrip("\r\n"))

    main_labels = structures["main"]["identifiers"]["label"]
    eoce_labels = structures["eoce"]["identifiers"]["label"]
    require(main_labels == [
        "negativeBinomial",
        "eachSeqOfSixTriesToGetFourSuccesses",
        "successFailureOrdersForBriansFieldGoals",
        "probOfEachSeqOfSixTriesToGetFourSuccesses",
    ], "B017 main labels changed")
    require(eoce_labels == ["roll_die", "play_darts", "sampling_at_school", "serving_volleyball"], "B017 EoCE labels changed")
    require(structures["main"]["identifiers"]["input"] == [EOCE_PATH], "B017 EoCE input linkage changed")

    combined = "\n".join(targets.values())
    expected_indonesian = [
        "Distribusi binomial negatif",
        "distribusi geometrik",
        "Apakah kasusnya binomial negatif?",
        "Melempar dadu",
        "Bermain dart",
        "Pengambilan sampel di sekolah",
        "Servis dalam bola voli",
        "Geometrik, 0.0804",
        "Binomial negatif, 0.0193",
    ]
    absent = [phrase for phrase in expected_indonesian if phrase.casefold() not in combined.casefold()]
    require(not absent, f"expected B017 Indonesian reader text absent: {absent}")
    forbidden_english = [
        "The geometric distribution describes",
        "To identify a negative binomial case",
        "Suppose Brian is very diligent",
        "The negative binomial distribution requires",
        "Rolling a die",
        "Playing darts",
        "Sampling at school",
        "Serving in volleyball",
        "Negative binomial with $n=4$",
    ]
    forbidden_counts = {phrase: combined.casefold().count(phrase.casefold()) for phrase in forbidden_english}
    require(not any(forbidden_counts.values()), f"reader-visible English remains in B017 candidates: {forbidden_counts}")

    main = targets["main"]
    eoce = targets["eoce"]
    answers = targets["answers"]
    require(main.count("\\begin{examplewrap}") == 3, "B017 worked-example count changed")
    require(main.count("\\begin{exercisewrap}") == 5, "B017 guided-exercise count changed")
    require(main.count("\\footnotetext{") == 5, "B017 guided public-answer count changed")
    require(main.count("\\begin{onebox}") == 3, "B017 onebox count changed")
    require(main.count("\\D{\\newpage}") == 3, "B017 forced display-page-break count changed")
    require(main.count("\\begin{figure}") == 1 and "\\includegraphics" not in main, "B017 inline-figure closure changed")
    require(eoce.count("\\eoce{") == 4, "B017 EoCE exercise count changed")
    require(eoce.count("\\item ") == 13, "B017 EoCE part count changed")
    require(re.findall(r"(?m)^% (\d+)$", eoce) == ["27", "28", "29", "30"], "B017 EoCE IDs changed")
    require(re.findall(r"(?m)^% (\d+)$", answers) == ["27", "29"], "B017 public-answer IDs changed")
    require(answers.count("\\eocesol{") == 2, "B017 public-answer block count changed")
    require("% 28" not in answers and "% 30" not in answers, "B017 O001 gaps were unexpectedly answered")

    recomputed = {
        "single_sequence": (1 - 0.8) ** 2 * 0.8**4,
        "ten_sequences": math.comb(5, 3) * (1 - 0.8) ** 2 * 0.8**4,
        "within_five": 0.8**4 + math.comb(4, 3) * 0.8**4 * 0.2,
        "hospital_a": math.comb(7, 3) * 0.7**3 * 0.3**4,
        "hospital_b": math.comb(3, 1) * 0.7**2 * 0.3**2,
        "hospital_c": 0.3**4 * 0.7,
        "eoce_27_a": (5 / 6) ** 4 * (1 / 6),
        "eoce_27_b": math.comb(5, 3) * (1 / 6) ** 3 * (5 / 6) ** 2,
        "eoce_27_c": math.comb(4, 2) * (1 / 6) ** 3 * (5 / 6) ** 2,
        "eoce_29_b": math.comb(3, 1) * 0.55**2 * 0.45**2,
    }
    expected_values = {
        "single_sequence": 0.016384,
        "ten_sequences": 0.16384,
        "within_five": 0.73728,
        "hospital_a": 0.0972405,
        "hospital_b": 0.1323,
        "hospital_c": 0.00567,
        "eoce_27_a": 0.08037551440329219,
        "eoce_27_b": 0.03215020576131687,
        "eoce_27_c": 0.01929012345679012,
        "eoce_29_b": 0.18376875,
    }
    require(all(math.isclose(recomputed[key], value, rel_tol=0, abs_tol=1e-14) for key, value in expected_values.items()), "B017 formula recomputation changed")
    formula_witnesses = [
        "{n-1 \\choose k-1}",
        "p^{k}(1-p)^{n-k}",
        "0.0164",
        "0.164",
        "0.74",
        "0.097",
        "0.132",
        "0.006",
        "0.0804",
        "0.0322",
        "0.0193",
        "0.1838",
    ]
    require(all(value in combined for value in formula_witnesses), "one or more B017 formula/result witnesses are absent")

    return {
        "exact_inputs": exact,
        "authority_files": authority,
        "authority_spans": span_receipts,
        "structures": structures,
        "coverage": {
            "section": "4.4 Distribusi binomial negatif / negativeBinomial",
            "subsections": 0,
            "worked_examples": 3,
            "guided_exercises": 5,
            "guided_inline_public_answers": 5,
            "onebox_blocks": 3,
            "inline_tex_figures": 1,
            "eoce_ids": [27, 28, 29, 30],
            "public_answer_ids": [27, 29],
            "o001_missing_public_answers": [28, 30],
        },
        "language": {
            "expected_indonesian": expected_indonesian,
            "absent": [],
            "forbidden_english_counts": forbidden_counts,
        },
        "mathematics": {
            "formula_parameters_operators_and_results_changed": False,
            "recomputed_values": recomputed,
            "formula_witnesses": formula_witnesses,
        },
        "rights": {
            "boundary_content": "CC BY-SA 3.0 Unported repository-declared text and inline TeX table figure",
            "new_external_assets": 0,
            "new_code_files": 0,
            "new_data_files": 0,
            "brand_exclusion_preserved": True,
        },
        "upstream_copyedit_candidates_recorded_not_applied": 8,
        "semantic_source_corrections_applied": 0,
        "restricted_instructor_solutions_accessed": False,
        "restricted_solutions_invented": False,
        "unresolved_candidate_issues": [],
    }


def splice_between(base: bytes, start_marker: bytes, end_marker: bytes, fragment: bytes, label: str) -> tuple[bytes, dict[str, Any]]:
    start = base.find(start_marker)
    end = base.find(end_marker, start + len(start_marker))
    require(start >= 0 and end > start, f"{label} splice markers absent")
    require(base.find(start_marker, start + 1) < 0, f"{label} start marker not unique")
    require(base.find(end_marker, end + 1) < 0, f"{label} end marker not unique")
    removed = base[start:end]
    return base[:start] + fragment + base[end:], {
        "base_prefix_bytes": start,
        "base_suffix_bytes": len(base) - end,
        "removed_bytes": len(removed),
        "removed_sha256": hashlib.sha256(removed).hexdigest(),
        "replacement_bytes": len(fragment),
        "replacement_sha256": hashlib.sha256(fragment).hexdigest(),
        "prefix_and_suffix_preserved_byte_exact": True,
    }


def assemble_main(base: bytes) -> tuple[bytes, dict[str, Any]]:
    return splice_between(
        base,
        b"\\section{Negative binomial distribution}",
        b"\\section{Poisson distribution}",
        MAIN_FRAGMENT.read_bytes(),
        "Section 4.4",
    )


def assemble_answers(base: bytes) -> tuple[bytes, dict[str, Any]]:
    chapter = base.find(b"\\eocesolch{Distribusi variabel acak}")
    next_chapter = base.find(b"\\eocesolch", chapter + 1)
    require(chapter >= 0 and next_chapter > chapter, "Chapter 4 public-answer region absent")
    start = base.find(b"% 27", chapter, next_chapter)
    end = base.find(b"\\end{multicols}", start, next_chapter)
    require(start >= 0 and end > start, "Chapter 4 public-answer 27/29 anchors absent")
    require(base[start:end].count(b"% 27") == 1 and base[start:end].count(b"% 29") == 1, "base public-answer 27/29 closure changed")
    require(b"% 31" not in base[start:end], "answer splice crossed into exercise 31")
    removed = base[start:end]
    fragment = ANSWER_FRAGMENT.read_bytes().rstrip(b"\r\n") + b"\n\n"
    return base[:start] + fragment + base[end:], {
        "chapter_region_unique": True,
        "following_multicolumn_transition_preserved": True,
        "base_prefix_bytes": start,
        "base_suffix_bytes": len(base) - end,
        "removed_bytes": len(removed),
        "removed_sha256": hashlib.sha256(removed).hexdigest(),
        "replacement_substantive_bytes": ANSWER_FRAGMENT.stat().st_size,
        "replacement_bytes_with_separator": len(fragment),
        "replacement_substantive_sha256": hashlib.sha256(ANSWER_FRAGMENT.read_bytes()).hexdigest(),
        "prefix_and_suffix_preserved_byte_exact": True,
    }


def source_checks(snapshot: Path, splice_qa: dict[str, Any], verified: dict[str, Any]) -> dict[str, Any]:
    main = (snapshot / MAIN_PATH).read_bytes()
    eoce = (snapshot / EOCE_PATH).read_bytes()
    answers = (snapshot / ANSWERS_PATH).read_bytes()
    start = main.find(b"\\section{Distribusi binomial negatif}")
    end = main.find(b"\\section{Poisson distribution}", start)
    require(start >= 0 and end > start, "assembled B017 main boundary absent")
    require(main[start:end] == MAIN_FRAGMENT.read_bytes(), "assembled B017 main fragment is not byte-exact")
    require(eoce == EOCE_FRAGMENT.read_bytes(), "assembled B017 EoCE file is not byte-exact")
    chapter = answers.find(b"\\eocesolch{Distribusi variabel acak}")
    answer_start = answers.find(b"% 27", chapter)
    answer_end = answers.find(b"\\end{multicols}", answer_start)
    answer_region = answers[answer_start:answer_end].rstrip(b"\r\n")
    require(answer_region == ANSWER_FRAGMENT.read_bytes().rstrip(b"\r\n"), "assembled B017 public answers are not byte-exact")
    require(b"\\section{Negative binomial distribution}" not in main[start:end], "English B017 section title remains")
    require(b"\\section{Poisson distribution}" in main[end:], "next cursor section was not preserved")
    return {
        "splice_qa": splice_qa,
        "assembled_overlays": {
            path: shared.identity_under(snapshot / path, snapshot) for path in sorted(MODIFIED_PATHS)
        },
        "candidate_structure": verified["structures"],
        "coverage": verified["coverage"],
        "language": verified["language"],
        "mathematics": verified["mathematics"],
        "exercise_answer_closure_exact": True,
        "unrelated_manifest_paths_preserved_byte_exact": 1203,
        "next_cursor_preserved": {"section": "Poisson distribution", "label": "poisson", "authority_line": 2111},
    }


def prepare_snapshot(rows: dict[str, tuple[int, str]], base: dict[str, Any], verified: dict[str, Any]) -> dict[str, tuple[int, str]]:
    require(not BUILD_ROOT.exists(), f"refusing to overwrite existing B017 build output: {rel(BUILD_ROOT)}")
    for path in (SNAPSHOT, SOURCE_MANIFEST, SOURCE_QA, RUN_A, RUN_B, FINAL, REVIEW_RENDER):
        require_build_path(path)
    BUILD_ROOT.mkdir(parents=True)
    shutil.copytree(BASE_SNAPSHOT, SNAPSHOT)
    base_rows = dict(rows)
    main, main_qa = assemble_main((BASE_SNAPSHOT / MAIN_PATH).read_bytes())
    answers, answers_qa = assemble_answers((BASE_SNAPSHOT / ANSWERS_PATH).read_bytes())
    assembled = {
        MAIN_PATH: main,
        EOCE_PATH: EOCE_FRAGMENT.read_bytes(),
        ANSWERS_PATH: answers,
    }
    for relative, raw in assembled.items():
        destination = SNAPSHOT / relative
        require_build_path(destination)
        destination.write_bytes(raw)
        rows[relative] = (len(raw), hashlib.sha256(raw).hexdigest())
    require(all(rows[path] == base_rows[path] for path in rows if path not in MODIFIED_PATHS), "an unrelated B016 manifest identity changed")
    rows = dict(sorted(rows.items()))
    SOURCE_MANIFEST.write_text(
        "".join(f"{path}\t{size}\t{digest}\n" for path, (size, digest) in rows.items()),
        encoding="utf-8",
        newline="\n",
    )
    inventory = shared.verify_manifest_snapshot(SNAPSHOT, rows)
    checks = source_checks(SNAPSHOT, {"main": main_qa, "public_answers": answers_qa, "eoce_full_file": True}, verified)
    source_qa = {
        "$schema": "interlanguage.r011-b017-isolated-source-qa/v1",
        "boundary_id": BOUNDARY_ID,
        "status": "PASS_EXACT_ADMITTED_B016_MANIFEST_PLUS_THREE_B017_OVERLAYS",
        "authority": {"commit": AUTHORITY_COMMIT, "tree": AUTHORITY_TREE},
        "base_boundary": "R011-B016",
        "base_evidence": base,
        "terminal_inputs": verified,
        "builder": identity(Path(__file__)),
        "source_manifest": {**identity(SOURCE_MANIFEST), "files": len(rows)},
        "snapshot": {"path": rel(SNAPSHOT), **inventory},
        "translated_component_count": 3,
        "modified_manifest_path_count": 3,
        "checks": checks,
        "translation_scope": "Complete Section 4.4 Distribusi binomial negatif; five guided exercises and public inline answers; EoCE 27-30; public answers 27/29; O001 gaps 28/30; one inline TeX table figure; no external assets, code, or data.",
        "o001_gaps": [28, 30],
        "production_model": MODEL,
        "rights": verified["rights"],
        "canonical_mutation": False,
        "backend_mutation": False,
        "control_mutation": False,
        "output_mutation": False,
        "release_mutation": False,
        "git_used": False,
        "network_used": False,
        "credentials_inspected": False,
        "publication_performed": False,
        "upstream_contact": False,
    }
    SOURCE_QA.write_bytes(canonical_json(source_qa))
    return rows


def page_texts(path: Path) -> list[str]:
    return path.read_text(encoding="utf-8", errors="replace").split("\f")


def first_page(pages: list[str], phrases: Iterable[str], minimum: int = 1, maximum: int | None = None) -> int | None:
    folded = [phrase.casefold() for phrase in phrases]
    limit = len(pages) if maximum is None else min(maximum, len(pages))
    for page in range(max(1, minimum), limit + 1):
        value = pages[page - 1].casefold()
        if all(phrase in value for phrase in folded):
            return page
    return None


def first_page_regex(pages: list[str], pattern: str, minimum: int = 1, maximum: int | None = None) -> int | None:
    limit = len(pages) if maximum is None else min(maximum, len(pages))
    compiled = re.compile(pattern, flags=re.IGNORECASE | re.MULTILINE)
    for page in range(max(1, minimum), limit + 1):
        if compiled.search(pages[page - 1]):
            return page
    return None


def locate_pages(text_path: Path) -> dict[str, Any]:
    pages = page_texts(text_path)
    # The chapter-opening contents page also lists the section title.  Bind the
    # real instructional opening by requiring text from its first onebox, not
    # merely the title occurrence in the chapter contents.
    section_start = first_page(
        pages,
        ["Distribusi binomial negatif", "Apakah kasusnya binomial negatif?"],
        minimum=130,
        maximum=250,
    )
    require(section_start is not None, "Section 4.4 Indonesian start page absent")
    next_section = first_page(pages, ["Poisson distribution"], minimum=section_start + 1, maximum=260)
    require(next_section is not None, "Section 4.5 transition page absent")
    eoce_start = first_page(pages, ["Melempar dadu"], minimum=section_start, maximum=next_section)
    eoce_end = first_page(pages, ["Servis dalam bola voli"], minimum=eoce_start or section_start, maximum=next_section)
    require(eoce_start is not None and eoce_end is not None and eoce_end >= eoce_start, "B017 EoCE page closure absent")
    answer_start = first_page_regex(pages, r"4\.27\s+\(a\)", minimum=350, maximum=430)
    require(answer_start is not None, "B017 public answer 4.27 page absent")
    answer_next = first_page_regex(pages, r"4\.31\s+\(a\)", minimum=answer_start, maximum=430)
    if answer_next is None:
        answer_next = first_page(pages, ["4.31", "Poisson"], minimum=answer_start, maximum=430)
    require(answer_next is not None and answer_next >= answer_start, "public answer 27-to-31 boundary absent")
    return {
        "section_start_page": section_start,
        "eoce_start_page": eoce_start,
        "eoce_end_page": eoce_end,
        "next_section_page": next_section,
        "public_answer_start_page": answer_start,
        "public_answer_next_page": answer_next,
        "section_eoce_and_transition_window": [max(1, section_start - 1), min(len(pages), next_section + 1)],
        "public_answer_and_transition_window": [max(1, answer_start - 1), min(len(pages), answer_next + 1)],
        "transition": "Section 4.4 / Distribusi binomial negatif -> Section 4.5 / Poisson distribution",
    }


def reader_checks(text_path: Path, mapping: dict[str, Any]) -> dict[str, Any]:
    pages = page_texts(text_path)
    section_text = "\n".join(pages[mapping["section_start_page"] - 1 : mapping["next_section_page"]])
    expected = [
        "Distribusi binomial negatif",
        "Apakah kasusnya binomial negatif?",
        "Percobaan Tendangan",
        "Binomial versus binomial negatif",
        "Melempar dadu",
        "Bermain dart",
        "Pengambilan sampel di sekolah",
        "Servis dalam bola voli",
    ]
    absent = [value for value in expected if value.casefold() not in section_text.casefold()]
    require(not absent, f"reader text lacks B017 Indonesian terms: {absent}")
    forbidden = [
        "The geometric distribution describes",
        "Is it negative binomial?",
        "Kick Attempt",
        "Binomial versus negative binomial",
        "Rolling a die",
        "Playing darts",
        "Sampling at school",
        "Serving in volleyball",
    ]
    forbidden_counts = {value: section_text.casefold().count(value.casefold()) for value in forbidden}
    require(not any(forbidden_counts.values()), f"reader-visible B017 English remains: {forbidden_counts}")

    a0, a1 = mapping["public_answer_and_transition_window"]
    answer_window = "\n".join(pages[a0 - 1 : a1])
    require("4.27" in answer_window and "4.29" in answer_window, "B017 public answer numbering incomplete")
    require("Geometrik, 0.0804" in answer_window, "localized public answer 4.27 absent")
    require("Binomial negatif" in answer_window and "0.1838" in answer_window, "localized public answer 4.29 absent")
    answer_forbidden = ["Geometric, 0.0804", "Negative binomial with", "In the binomial model"]
    answer_counts = {value: answer_window.casefold().count(value.casefold()) for value in answer_forbidden}
    require(not any(answer_counts.values()), f"public-answer English remains: {answer_counts}")
    return {
        "status": "PASS_EXACT_READER_TEXT_MATHEMATICS_AND_ANSWER_CLOSURE",
        "expected_indonesian": expected,
        "absent": [],
        "translated_boundary_forbidden_phrase_counts": forbidden_counts,
        "localized_public_answer_forbidden_phrase_counts": answer_counts,
        "eoce_ids": [27, 28, 29, 30],
        "public_answer_ids": [27, 29],
        "o001_gaps": [28, 30],
        "inline_tex_figure_count": 1,
        "external_asset_count": 0,
    }


def expected_review_pages(mapping: dict[str, Any]) -> set[int]:
    pages: set[int] = set()
    for key in ("section_eoce_and_transition_window", "public_answer_and_transition_window"):
        start, end = mapping[key]
        pages.update(range(start, end + 1))
    return pages


def render_review_pages(pdf: Path, mapping: dict[str, Any], toolchain: dict[str, str]) -> list[dict[str, Any]]:
    require(not REVIEW_RENDER.exists(), "B017 review render directory already exists")
    REVIEW_RENDER.mkdir(parents=True)
    artifacts: list[dict[str, Any]] = []
    for page in sorted(expected_review_pages(mapping)):
        prefix = REVIEW_RENDER / f"page-{page:04d}"
        completed = subprocess.run(
            [toolchain["pdftoppm"], "-f", str(page), "-l", str(page), "-png", "-r", str(REVIEW_DPI), str(pdf), str(prefix)],
            capture_output=True,
        )
        require(completed.returncode == 0, f"B017 review render failed on page {page}")
        candidates = sorted(REVIEW_RENDER.glob(f"page-{page:04d}-*.png"))
        require(len(candidates) == 1, f"unexpected B017 render inventory for page {page}")
        artifacts.append({"page": page, **identity(candidates[0])})
    require({item["page"] for item in artifacts} == expected_review_pages(mapping), "B017 review pages incomplete")
    return artifacts


def verify_toolchain(toolchain: dict[str, str]) -> dict[str, Any]:
    base = read_json(BASE_BUILD_RECEIPT).get("toolchain", {})
    observed = {name: shared.tool_identity(name, Path(path)) for name, path in toolchain.items()}
    require(set(observed) == set(base), "B017/B016 toolchain name set changed")
    for name, item in observed.items():
        require((item["bytes"], item["sha256"]) == (base[name]["bytes"], base[name]["sha256"]), f"B016 toolchain identity changed: {name}")
    return observed


def require_record_identity(record: dict[str, Any], path: Path, label: str) -> dict[str, Any]:
    observed = identity(path)
    require(
        (record.get("bytes"), record.get("sha256")) == (observed["bytes"], observed["sha256"]),
        f"{label} identity changed",
    )
    return observed


def load_b017_manifest() -> dict[str, tuple[int, str]]:
    rows: dict[str, tuple[int, str]] = {}
    for line_number, line in enumerate(SOURCE_MANIFEST.read_text(encoding="utf-8").splitlines(), 1):
        parts = line.split("\t")
        require(len(parts) == 3, f"malformed B017 source manifest line {line_number}")
        path, size_text, digest = parts
        require(path not in rows, f"duplicate B017 manifest path: {path}")
        require(re.fullmatch(r"[0-9a-f]{64}", digest) is not None, f"invalid B017 manifest digest on line {line_number}")
        rows[path] = (int(size_text), digest)
    require(len(rows) == 1206, f"B017 source manifest row count changed: {len(rows)}")
    return rows


def verify_existing_build() -> tuple[dict[str, Any], dict[str, Any]]:
    """Reprove the completed replays without rebuilding or overwriting them."""
    pre = read_json(BUILD_RECEIPT)
    require(pre.get("boundary_id") == BOUNDARY_ID, "existing build receipt boundary changed")
    require(pre.get("status") == "PASS_ISOLATED_TWO_REPLAY_DETERMINISTIC_BUILD_VISUAL_INSPECTION_PENDING", "existing build receipt is not the expected deterministic pre-visual PASS")
    require(pre.get("page_count") == 428, "existing B017 page count changed")
    require_record_identity(pre["candidate_artifact"], FINAL_PDF, "existing candidate PDF")
    require_record_identity(pre["candidate_text"], FINAL_TEXT, "existing candidate text")
    require_record_identity(pre["source_manifest"], SOURCE_MANIFEST, "existing source manifest")
    require_record_identity(pre["source_qa"], SOURCE_QA, "existing source QA")
    source_qa = read_json(SOURCE_QA)
    require(source_qa.get("status") == "PASS_EXACT_ADMITTED_B016_MANIFEST_PLUS_THREE_B017_OVERLAYS", "existing B017 source QA status changed")
    rows = load_b017_manifest()
    snapshot = shared.verify_manifest_snapshot(SNAPSHOT, rows)
    require(
        pre.get("snapshot", {}).get("inventory_sha256") == snapshot["inventory_sha256"],
        "existing B017 snapshot inventory digest changed",
    )

    determinism = pre.get("determinism", {})
    run_a = determinism.get("complete_build_replay_a", {})
    run_b = determinism.get("complete_build_replay_b", {})
    for label, run, directory in (("replay-a", run_a, RUN_A), ("replay-b", run_b, RUN_B)):
        require(run.get("page_count") == 428, f"{label} page count changed")
        pdf = require_record_identity(run["pdf"], directory / "main.pdf", f"{label} PDF")
        text = require_record_identity(run["text"], directory / "main-final.txt", f"{label} text")
        require_record_identity(run["pass3"], directory / "main-pass3.pdf", f"{label} pass-3 PDF")
        require((pdf["bytes"], pdf["sha256"]) == (run["pass4"]["bytes"], run["pass4"]["sha256"]), f"{label} pass-4 identity changed")
        require(not any(run.get("warnings", {}).get("fatal_terminal_counts", {}).values()), f"{label} now reports terminal LaTeX warnings")
        require(text["bytes"] > 0, f"{label} extracted text is empty")
    require(
        (run_a["pdf"]["bytes"], run_a["pdf"]["sha256"]) == (run_b["pdf"]["bytes"], run_b["pdf"]["sha256"]),
        "existing replay PDFs differ",
    )
    require(
        (run_a["text"]["bytes"], run_a["text"]["sha256"]) == (run_b["text"]["bytes"], run_b["text"]["sha256"]),
        "existing replay text extractions differ",
    )
    require(run_a.get("trailer_ids") == run_b.get("trailer_ids"), "existing replay trailer IDs differ")
    require(all(determinism.get(key) is True for key in (
        "each_replay_pass3_pass4_byte_identical",
        "replay_pdfs_byte_identical",
        "replay_text_extractions_byte_identical",
        "all_complete_pdf_instances_byte_identical",
        "trailer_ids_equal",
    )), "existing determinism flags are incomplete")
    return pre, {"rows": len(rows), "snapshot": snapshot, "run_a": run_a, "run_b": run_b}


def collect_visual_artifacts(pages: Iterable[int]) -> list[dict[str, Any]]:
    artifacts: list[dict[str, Any]] = []
    for page in sorted(set(pages)):
        candidates = sorted(REVIEW_RENDER.glob(f"page-{page:04d}-*.png"))
        require(len(candidates) == 1, f"existing visual render inventory changed for page {page}")
        artifacts.append({"page": page, **identity(candidates[0])})
    return artifacts


def write_idempotent_or_exact_metadata_upgrade(
    path: Path,
    raw: bytes,
    exact_upgrade_preimage: tuple[int, str],
    label: str,
) -> None:
    """Write once, remain idempotent, or upgrade one exact known receipt."""
    if not path.exists():
        path.write_bytes(raw)
        return
    if path.read_bytes() == raw:
        return
    observed = identity(path)
    require(
        (observed["bytes"], observed["sha256"]) == exact_upgrade_preimage,
        f"refusing to overwrite non-identical {label}",
    )
    path.write_bytes(raw)


def finalize_existing() -> dict[str, Any]:
    """Finalize a completed build after bounded visual inspection, idempotently."""
    load_manifest()
    verify_base(load_manifest())
    verified = verify_inputs()
    toolchain = verify_toolchain(shared.tools())
    pre, replay_proof = verify_existing_build()
    mapping = locate_pages(FINAL_TEXT)
    require(mapping["section_start_page"] == 163, "actual B017 section opening moved")
    require(mapping["eoce_start_page"] == mapping["eoce_end_page"] == 167, "B017 EoCE page mapping changed")
    require(mapping["next_section_page"] == 168, "B017-to-Poisson transition moved")
    require(mapping["public_answer_start_page"] == 395 and mapping["public_answer_next_page"] == 396, "B017 public-answer mapping changed")
    text_qa = reader_checks(FINAL_TEXT, mapping)
    inspection_pages = list(range(163, 170)) + list(range(394, 398))
    renders = collect_visual_artifacts(inspection_pages)
    visual = {
        "$schema": "interlanguage.r011-b017-visual-qa/v1",
        "boundary_id": BOUNDARY_ID,
        "status": "PASS_ZERO_VISUAL_DEFECTS_IN_BOUNDARY_AND_TRANSITION_WINDOWS",
        "candidate_artifact": identity(FINAL_PDF),
        "candidate_text": identity(FINAL_TEXT),
        "pre_visual_build_receipt": identity(BUILD_RECEIPT),
        "locator_correction": {
            "prior_overinclusive_section_start_page": pre.get("affected_page_mapping", {}).get("section_start_page"),
            "cause": "The prior locator matched the Section 4.4 title listed on the Chapter 4 contents page.",
            "corrected_instructional_section_start_page": 163,
            "method": "Require both the localized section title and its first localized negative-binomial conditions box on the same page.",
            "deterministic_build_outputs_changed": False,
        },
        "affected_page_mapping": mapping,
        "inspection": {
            "model": MODEL,
            "render_dpi": REVIEW_DPI,
            "translated_section_and_eoce_pages": [163, 164, 165, 166, 167],
            "next_cursor_transition_pages": [168, 169],
            "public_answer_primary_page": 395,
            "public_answer_context_pages": [394, 395, 396, 397],
            "pages_inspected": inspection_pages,
            "checks": [
                "centered and readable page composition",
                "legible body text and headings",
                "no clipping or overlap",
                "equations and inline TeX table intact",
                "footnotes intact",
                "EoCE and public-answer layout intact",
                "boundary transitions intact",
            ],
            "defects": [],
            "defect_count": 0,
        },
        "cursor_design_note": "Poisson content on pages 168-169 and public answers from 4.31 onward remain English because Poisson is the next, explicitly excluded source cursor.",
        "render_artifacts": renders,
        "admission_authorized": True,
        "production_model": MODEL,
        "canonical_mutation": False,
        "backend_mutation": False,
        "control_mutation": False,
        "output_mutation": False,
        "release_mutation": False,
        "git_used": False,
        "network_used": False,
        "credentials_inspected": False,
        "publication_performed": False,
        "upstream_contact": False,
    }
    visual_raw = canonical_json(visual)
    write_idempotent_or_exact_metadata_upgrade(
        VISUAL_QA,
        visual_raw,
        PRE_ADMISSION_FLAG_VISUAL_QA,
        "B017 visual QA",
    )

    final = dict(pre)
    final.update({
        "$schema": "interlanguage.r011-b017-final-candidate-build-qa/v1",
        "status": "PASS_ISOLATED_TWO_REPLAY_DETERMINISTIC_BUILD_ZERO_VISUAL_DEFECTS",
        "pre_visual_build_receipt": identity(BUILD_RECEIPT),
        "finalizer": identity(Path(__file__)),
        "affected_page_mapping": mapping,
        "reader_checks": text_qa,
        "visual": {
            "status": visual["status"],
            "defect_count": 0,
            "pages": inspection_pages,
            "qa_receipt": identity(VISUAL_QA),
            "admission_authorized": True,
        },
        "existing_build_reverification": {
            "status": "PASS_EXACT_NO_REBUILD",
            "manifest_rows": replay_proof["rows"],
            "snapshot": replay_proof["snapshot"],
            "replay_a_pdf": replay_proof["run_a"]["pdf"],
            "replay_b_pdf": replay_proof["run_b"]["pdf"],
            "replay_pdfs_byte_identical": True,
            "replay_text_extractions_byte_identical": True,
            "terminal_latex_warning_counts_zero": True,
            "toolchain": toolchain,
        },
        "terminal_inputs": verified,
        "locator_correction_changed_pdf_or_text_bytes": False,
    })
    final_raw = canonical_json(final)
    write_idempotent_or_exact_metadata_upgrade(
        FINAL_BUILD_RECEIPT,
        final_raw,
        PRE_ADMISSION_FLAG_FINAL_RECEIPT,
        "B017 final build receipt",
    )
    final["final_build_receipt"] = identity(FINAL_BUILD_RECEIPT)
    final["write_root"] = rel(BUILD_ROOT)
    return final


def self_test() -> dict[str, Any]:
    rows = load_manifest()
    base = verify_base(rows)
    verified = verify_inputs()
    toolchain_paths = shared.tools()
    toolchain = verify_toolchain(toolchain_paths)
    for path in (SNAPSHOT, SOURCE_MANIFEST, SOURCE_QA, RUN_A, RUN_B, FINAL, FINAL_PDF, FINAL_TEXT, BUILD_RECEIPT, FINAL_BUILD_RECEIPT, REVIEW_RENDER, VISUAL_QA):
        require_build_path(path)
    return {
        "boundary_id": BOUNDARY_ID,
        "status": "PASS_INERT_EXACT_B016_BASE_AUTHORITY_CANDIDATES_AND_TOOLCHAIN_BOUND",
        "builder": identity(Path(__file__)),
        "base": base,
        "terminal_inputs": verified,
        "toolchain": toolchain,
        "write_root": rel(BUILD_ROOT),
        "writes_performed": False,
        "canonical_repo_inspected": False,
        "canonical_mutation": False,
        "git_used": False,
        "network_used": False,
        "credentials_inspected": False,
    }


def execute_build() -> dict[str, Any]:
    rows = load_manifest()
    base = verify_base(rows)
    verified = verify_inputs()
    toolchain_paths = shared.tools()
    toolchain = verify_toolchain(toolchain_paths)
    rows = prepare_snapshot(rows, base, verified)
    trailer_seed = hashlib.sha256(SOURCE_MANIFEST.read_bytes()).hexdigest()[:32].upper()
    run_a = shared.build_once("replay-a", RUN_A, toolchain_paths, trailer_seed, replace=False)
    run_b = shared.build_once("replay-b", RUN_B, toolchain_paths, trailer_seed, replace=False)
    require((run_a["pdf"]["bytes"], run_a["pdf"]["sha256"]) == (run_b["pdf"]["bytes"], run_b["pdf"]["sha256"]), "complete B017 replay PDFs differ")
    require((run_a["text"]["bytes"], run_a["text"]["sha256"]) == (run_b["text"]["bytes"], run_b["text"]["sha256"]), "complete B017 replay text differs")
    require(run_a["page_count"] == run_b["page_count"], "complete B017 replay page counts differ")
    require(run_a["trailer_ids"] == run_b["trailer_ids"], "complete B017 replay trailer IDs differ")

    FINAL.mkdir(parents=True)
    shutil.copy2(RUN_A / "main.pdf", FINAL_PDF)
    shutil.copy2(RUN_A / "main-final.txt", FINAL_TEXT)
    final_pdf = identity(FINAL_PDF)
    final_text = identity(FINAL_TEXT)
    require((final_pdf["bytes"], final_pdf["sha256"]) == (run_a["pdf"]["bytes"], run_a["pdf"]["sha256"]), "final B017 PDF copy changed")
    require((final_text["bytes"], final_text["sha256"]) == (run_a["text"]["bytes"], run_a["text"]["sha256"]), "final B017 text copy changed")
    mapping = locate_pages(FINAL_TEXT)
    text_qa = reader_checks(FINAL_TEXT, mapping)
    renders = render_review_pages(FINAL_PDF, mapping, toolchain_paths)
    receipt = {
        "$schema": "interlanguage.r011-b017-isolated-candidate-build-qa/v1",
        "boundary_id": BOUNDARY_ID,
        "status": "PASS_ISOLATED_TWO_REPLAY_DETERMINISTIC_BUILD_VISUAL_INSPECTION_PENDING",
        "authority": {"commit": AUTHORITY_COMMIT, "tree": AUTHORITY_TREE},
        "base_boundary": "R011-B016",
        "base_evidence": base,
        "terminal_inputs": verified,
        "builder": identity(Path(__file__)),
        "source_manifest": {**identity(SOURCE_MANIFEST), "files": len(rows)},
        "source_qa": identity(SOURCE_QA),
        "snapshot": {"path": rel(SNAPSHOT), **shared.verify_manifest_snapshot(SNAPSHOT, rows)},
        "candidate_artifact": {**final_pdf, "promoted": False},
        "candidate_text": final_text,
        "determinism": {
            "complete_build_replay_a": run_a,
            "complete_build_replay_b": run_b,
            "each_replay_pass3_pass4_byte_identical": True,
            "replay_pdfs_byte_identical": True,
            "replay_text_extractions_byte_identical": True,
            "all_complete_pdf_instances_byte_identical": True,
            "trailer_ids_equal": True,
            "trailer_seed_source": "first 128 bits of SHA-256(R011-B017_SOURCE_MANIFEST.tsv)",
            "trailer_seed": trailer_seed.lower(),
            "established_b016_sequence": [
                "pdflatex pass 1", "bibtex", "makeindex 1", "pdflatex pass 2",
                "makeindex 2", "pdflatex pass 3", "makeindex 3", "pdflatex pass 4",
            ],
        },
        "page_count": run_a["page_count"],
        "affected_page_mapping": mapping,
        "reader_checks": text_qa,
        "exercise_answer_closure": {
            "eoce": [27, 28, 29, 30],
            "public": [27, 29],
            "o001_gaps": [28, 30],
            "restricted_instructor_solutions_accessed_or_invented": False,
            "exact": True,
        },
        "visual": {
            "status": "RENDERED_ONLY_NOT_YET_VISUALLY_INSPECTED",
            "render_dpi": REVIEW_DPI,
            "pages": [item["page"] for item in renders],
            "artifacts": renders,
        },
        "toolchain": toolchain,
        "translation_scope": "Complete Section 4.4 Distribusi binomial negatif; EoCE 27-30; public answers 27/29; O001 gaps 28/30; inline TeX table figure; no external assets, code, or data.",
        "rights": verified["rights"],
        "next_cursor": {"section": "Poisson distribution", "label": "poisson", "authority_line": 2111},
        "production_model": MODEL,
        "write_root": rel(BUILD_ROOT),
        "canonical_repo_inspected": False,
        "canonical_mutation": False,
        "backend_mutation": False,
        "control_mutation": False,
        "output_mutation": False,
        "release_mutation": False,
        "git_used": False,
        "network_used": False,
        "credentials_inspected": False,
        "publication_performed": False,
        "upstream_contact": False,
    }
    require(not BUILD_RECEIPT.exists(), "refusing to overwrite B017 build receipt")
    BUILD_RECEIPT.write_bytes(canonical_json(receipt))
    return receipt


def main() -> int:
    if sys.argv[1:] == ["--self-test"]:
        result = self_test()
    elif sys.argv[1:] == ["--build"]:
        result = execute_build()
    elif sys.argv[1:] == ["--finalize-existing"]:
        result = finalize_existing()
    else:
        raise SystemExit("usage: build_b017_candidate.py --self-test | --build | --finalize-existing")
    summary = {
        "boundary_id": result["boundary_id"],
        "status": result["status"],
        "builder": result["builder"],
        "write_root": result["write_root"],
    }
    if "page_count" in result:
        summary.update({
            "page_count": result["page_count"],
            "candidate_artifact": result["candidate_artifact"],
            "source_manifest": result["source_manifest"],
            "source_qa": result["source_qa"],
            "affected_page_mapping": result["affected_page_mapping"],
            "review_pages": result["visual"]["pages"],
        })
    if "final_build_receipt" in result:
        summary["final_build_receipt"] = result["final_build_receipt"]
    print(json.dumps(summary, ensure_ascii=False, sort_keys=True))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except GateError as exc:
        raise SystemExit(f"REFUSED: {exc}")
